namespace FSH.Modules.Suppliers.Contracts.Dtos;

public sealed record VendorDto(
    Guid Id,
    string Code,
    string Name,
    string RegisteredName,
    string RegistrationNo,
    string TaxId,
    string Type,
    string? LlrcTier,
    string Status,
    string Region,
    string State,
    string City,
    string Country,
    decimal Rating,
    string PaymentTerms,
    decimal CreditLimit,
    IReadOnlyList<string> Categories,
    IReadOnlyList<VendorContactDto> Contacts,
    IReadOnlyList<VendorAddressDto> Addresses,
    IReadOnlyList<VendorBankAccountDto> BankAccounts,
    IReadOnlyList<VendorCertificationDto> Certifications,
    IReadOnlyList<VendorCurrencyDto> Currencies,
    DateTime CreatedUtc,
    DateTime UpdatedUtc);
