namespace FSH.Modules.Procurement.Contracts.Dtos;

public sealed record PurchaseOrderDto(
    Guid Id,
    string Code,
    Guid? AwardId,
    Guid? RfqId,
    Guid? SourcePrId,
    string SourceKind,
    Guid VendorId,
    string Status,
    string Currency,
    Guid? ShipToLocationId,
    Guid? ShipToAddressId,
    string? ShipToAdhoc,
    Guid? IncotermId,
    string? IncotermCode,
    string? IncotermSuffix,
    string? Memo,
    string? VendorRef,
    DateOnly? RequiredDate,
    DateOnly? DeliveryDate,
    DateTime? VerifiedUtc,
    DateTime? IssuedUtc,
    Guid? EntryFormId,
    decimal TotalValue,
    IReadOnlyList<PoLineDto> Lines,
    DateTime CreatedUtc,
    DateTime UpdatedUtc,
    string VendorName = "");

public sealed record PoLineDto(
    Guid Id,
    string ItemCode,
    string Description,
    string Uom,
    decimal Qty,
    decimal UnitPrice,
    decimal ReceivedQty,
    decimal InvoicedQty,
    string? RfqLineCode,
    Guid? SourcePrLineId,
    Guid? TaxCodeId,
    bool PriceConfirmed,
    decimal LineTotal,
    decimal OpenQty = 0);

public sealed record PurchaseOrderListItemDto(
    Guid Id,
    string Code,
    Guid? RfqId,
    Guid? SourcePrId,
    string SourceKind,
    Guid VendorId,
    string Status,
    string Currency,
    decimal TotalValue,
    DateTime CreatedUtc,
    string VendorName = "",
    decimal ReceivedQty = 0,
    decimal TotalQty = 0,
    Guid? AwardId = null);
