// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using eProcure.Infrastructure.Persistence;

#nullable disable

namespace eProcure.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260701141802_SliceDPromotion")]
    partial class SliceDPromotion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("eProcure.Domain.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ActorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("After")
                        .HasColumnType("text");

                    b.Property<string>("Before")
                        .HasColumnType("text");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FromState")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ToState")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("UtcTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("UtcTimestamp");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("AuditEntries", (string)null);
                });

            modelBuilder.Entity("eProcure.Domain.Communication.Clarification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Published")
                        .HasColumnType("boolean");

                    b.Property<bool>("ReadByBuyer")
                        .HasColumnType("boolean");

                    b.Property<bool>("ReadByVendor")
                        .HasColumnType("boolean");

                    b.Property<string>("RecipientUserId")
                        .HasColumnType("text");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SenderKind")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Scope", "VendorId");

                    b.ToTable("Clarifications", (string)null);
                });

            modelBuilder.Entity("eProcure.Domain.Files.StoredFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("StoredFiles", (string)null);
                });

            modelBuilder.Entity("eProcure.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("eProcure.Domain.NumberSequence", b =>
                {
                    b.Property<string>("Prefix")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.Property<int>("LastValue")
                        .HasColumnType("integer");

                    b.HasKey("Prefix", "Year");

                    b.ToTable("NumberSequences", (string)null);
                });

            modelBuilder.Entity("eProcure.Domain.Onboarding.OnboardingClarificationRound", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("RaisedByName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RaisedByUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("RaisedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RespondedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RoundNo")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("ApplicationId", "RoundNo");

                    b.ToTable("OnboardingClarificationRounds", (string)null);
                });

            modelBuilder.Entity("eProcure.Domain.Onboarding.VendorFinancialAssessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VendorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId")
                        .IsUnique();

                    b.ToTable("VendorFinancialAssessments", (string)null);
                });

            modelBuilder.Entity("eProcure.Domain.Onboarding.VendorOnboardingApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Categories")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DecisionUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("InvitationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("PromotedVendorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RegisteredName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RegistrationNo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("RejectReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("SelectedTemplateIds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("SubmittedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TaxId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedUtc");

                    b.HasIndex("DecisionUtc");

                    b.HasIndex("InvitationId");

                    b.HasIndex("Source");

                    b.HasIndex("Status");

                    b.HasIndex("SubmittedUtc");

                    b.HasIndex("Type");

                    b.ToTable("VendorOnboardingApplications", (string)null);
                });

            modelBuilder.Entity("eProcure.Domain.Onboarding.VendorOnboardingInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("ExpiresUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InvitedByName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("InvitedByUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("OpenedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SelectedTemplateIds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("CreatedUtc");

                    b.HasIndex("Status");

                    b.HasIndex("TokenHash");

                    b.ToTable("VendorOnboardingInvitations", (string)null);
                });

            modelBuilder.Entity("eProcure.Domain.Procurement.Asn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Carrier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExpectedDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GrnCode")
                        .HasColumnType("text");

                    b.Property<Guid>("PoId")
                        .HasColumnType("uuid");

                    b.Property<string>("ShippedDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TrackingNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Asns", (string)null);
                });

            modelBuilder.Entity("eProcure.Domain.Procurement.Grn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AsnId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NsId")
                        .HasColumnType("text");

                    b.Property<Guid>("PoId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReceivedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReceivedDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Grns", (string)null);
                });

            modelBuilder.Entity("eProcure.Domain.Procurement.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExceptionReason")
                        .HasColumnType("text");

                    b.Property<string>("InvoiceNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NsId")
                        .HasColumnType("text");

                    b.Property<Guid>("PoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("WhtRate")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Invoices", (string)null);
                });

            modelBuilder.Entity("eProcure.Domain.Procurement.PurchaseOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Acknowledged")
                        .HasColumnType("boolean");

                    b.Property<string>("AwardCode")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Incoterm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NsId")
                        .HasColumnType("text");

                    b.Property<Guid?>("RfqId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("PurchaseOrders", (string)null);
                });

            modelBuilder.Entity("eProcure.Domain.Sourcing.Award", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApprovedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApproverUserId")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RfqId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("TotalValue")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Awards", (string)null);
                });

            modelBuilder.Entity("eProcure.Domain.Sourcing.Bid", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Lead")
                        .HasColumnType("integer");

                    b.Property<Guid>("RfqId")
                        .HasColumnType("uuid");

                    b.Property<bool>("SavedDraft")
                        .HasColumnType("boolean");

                    b.Property<bool>("Submitted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("SubmittedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid");

                    b.Property<int>("Warranty")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("RfqId", "VendorId")
                        .IsUnique();

                    b.ToTable("Bids", (string)null);
                });

            modelBuilder.Entity("eProcure.Domain.Sourcing.FormTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CommercialSections")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TechnicalSections")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Purpose");

                    b.ToTable("FormTemplates", (string)null);
                });

            modelBuilder.Entity("eProcure.Domain.Sourcing.PrLineSourcing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ClosedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LinkStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("PrLineId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("QtySourced")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("RfqId")
                        .HasColumnType("uuid");

                    b.Property<string>("RfqLineCode")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.HasIndex("LinkStatus");

                    b.HasIndex("PrLineId");

                    b.HasIndex("RfqId");

                    b.HasIndex("RfqLineCode");

                    b.ToTable("PrLineSourcings", (string)null);
                });

            modelBuilder.Entity("eProcure.Domain.Sourcing.PurchaseRequisition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CostCentre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("HeaderStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Job")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JobCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LocationCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Memo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Project")
                        .HasColumnType("text");

                    b.Property<string>("RaisedDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("RaisedOn")
                        .HasColumnType("date");

                    b.Property<string>("Requestor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequiredDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("RequiredOn")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Submitted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("HeaderStatus");

                    b.HasIndex("RaisedOn");

                    b.ToTable("PurchaseRequisitions", (string)null);
                });

            modelBuilder.Entity("eProcure.Domain.Sourcing.Rfq", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ClosesUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CommercialEvaluatorIds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("CommercialOpened")
                        .HasColumnType("boolean");

                    b.Property<string>("CommercialSections")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Envelope")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("InvitedVendorIds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("OpensUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OwnerUserId")
                        .HasColumnType("text");

                    b.Property<string>("PrRefs")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("TechFinalized")
                        .HasColumnType("boolean");

                    b.Property<string>("TechnicalEvaluatorIds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TechnicalOpened")
                        .HasColumnType("boolean");

                    b.Property<string>("TechnicalSections")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Rfqs", (string)null);
                });

            modelBuilder.Entity("eProcure.Domain.Sourcing.TechnicalScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Criterion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("EvaluatorId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("RfqId")
                        .HasColumnType("uuid");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RfqId", "VendorId", "EvaluatorId", "Criterion")
                        .IsUnique();

                    b.ToTable("TechnicalScores", (string)null);
                });

            modelBuilder.Entity("eProcure.Domain.Suppliers.SwecCategory", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsLeaf")
                        .HasColumnType("boolean");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ParentCode")
                        .HasColumnType("text");

                    b.Property<string>("PathText")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.HasKey("Code");

                    b.ToTable("SwecCategories", (string)null);
                });

            modelBuilder.Entity("eProcure.Domain.Suppliers.Vendor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Categories")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CreditLimit")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("LlrcTier")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PaymentTerms")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Rating")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RegisteredName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RegistrationNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TaxId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Vendors", (string)null);
                });

            modelBuilder.Entity("eProcure.Domain.Suppliers.VendorUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("VendorId");

                    b.ToTable("VendorUsers", (string)null);
                });

            modelBuilder.Entity("eProcure.Domain.Onboarding.OnboardingClarificationRound", b =>
                {
                    b.HasOne("eProcure.Domain.Onboarding.VendorOnboardingApplication", null)
                        .WithMany("Rounds")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("eProcure.Domain.Onboarding.OnboardingClarificationItem", "Items", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<Guid>("OnboardingClarificationRoundId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Request")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)");

                            b1.Property<string>("Response")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)");

                            b1.Property<string>("Topic")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)");

                            b1.HasKey("Id");

                            b1.HasIndex("OnboardingClarificationRoundId");

                            b1.ToTable("OnboardingClarificationItems", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("OnboardingClarificationRoundId");
                        });

                    b.Navigation("Items");
                });

            modelBuilder.Entity("eProcure.Domain.Onboarding.VendorFinancialAssessment", b =>
                {
                    b.HasOne("eProcure.Domain.Onboarding.VendorOnboardingApplication", null)
                        .WithOne("Financial")
                        .HasForeignKey("eProcure.Domain.Onboarding.VendorFinancialAssessment", "ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("eProcure.Domain.Onboarding.FinancialSnapshot", "Snapshots", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("AsOfUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Band")
                                .IsRequired()
                                .HasMaxLength(5)
                                .HasColumnType("character varying(5)");

                            b1.Property<string>("Risk")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<int>("Score")
                                .HasColumnType("integer");

                            b1.Property<string>("Stage")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<string>("Statement")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)");

                            b1.Property<Guid>("VendorFinancialAssessmentId")
                                .HasColumnType("uuid");

                            b1.Property<double>("WeightedZ")
                                .HasColumnType("double precision");

                            b1.HasKey("Id");

                            b1.HasIndex("VendorFinancialAssessmentId");

                            b1.ToTable("OnboardingFinancialSnapshots", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("VendorFinancialAssessmentId");
                        });

                    b.OwnsMany("eProcure.Domain.Onboarding.FinancialYearFigures", "Years", b1 =>
                        {
                            b1.Property<Guid>("VendorFinancialAssessmentId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<decimal>("CurrentAssets")
                                .HasColumnType("numeric(18,2)");

                            b1.Property<decimal>("CurrentLiabilities")
                                .HasColumnType("numeric(18,2)");

                            b1.Property<decimal>("Ebit")
                                .HasColumnType("numeric(18,2)");

                            b1.Property<decimal>("Equity")
                                .HasColumnType("numeric(18,2)");

                            b1.Property<decimal>("FixedAssets")
                                .HasColumnType("numeric(18,2)");

                            b1.Property<decimal>("Inventory")
                                .HasColumnType("numeric(18,2)");

                            b1.Property<decimal>("NetProfit")
                                .HasColumnType("numeric(18,2)");

                            b1.Property<decimal>("RetainedEarnings")
                                .HasColumnType("numeric(18,2)");

                            b1.Property<decimal>("Revenue")
                                .HasColumnType("numeric(18,2)");

                            b1.Property<decimal>("TotalAssets")
                                .HasColumnType("numeric(18,2)");

                            b1.Property<decimal>("TotalLiabilities")
                                .HasColumnType("numeric(18,2)");

                            b1.Property<int>("YearIndex")
                                .HasColumnType("integer");

                            b1.HasKey("VendorFinancialAssessmentId", "Id");

                            b1.HasIndex("YearIndex");

                            b1.ToTable("OnboardingFinancialYears", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("VendorFinancialAssessmentId");
                        });

                    b.Navigation("Snapshots");

                    b.Navigation("Years");
                });

            modelBuilder.Entity("eProcure.Domain.Onboarding.VendorOnboardingApplication", b =>
                {
                    b.OwnsMany("eProcure.Domain.Onboarding.OnboardingAnswer", "Answers", b1 =>
                        {
                            b1.Property<Guid>("VendorOnboardingApplicationId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("FormTemplateId")
                                .HasColumnType("uuid");

                            b1.Property<int>("QuestionOrder")
                                .HasColumnType("integer");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("character varying(4000)");

                            b1.HasKey("VendorOnboardingApplicationId", "Id");

                            b1.HasIndex("FormTemplateId");

                            b1.ToTable("OnboardingAnswers", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("VendorOnboardingApplicationId");
                        });

                    b.OwnsMany("eProcure.Domain.Onboarding.OnboardingDocument", "Documents", b1 =>
                        {
                            b1.Property<Guid>("VendorOnboardingApplicationId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasMaxLength(260)
                                .HasColumnType("character varying(260)");

                            b1.Property<string>("Key")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)");

                            b1.Property<Guid>("StoredFileId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("UploadedUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("VendorOnboardingApplicationId", "Id");

                            b1.ToTable("OnboardingDocuments", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("VendorOnboardingApplicationId");
                        });

                    b.OwnsMany("eProcure.Domain.Onboarding.OnboardingReviewStep", "Steps", b1 =>
                        {
                            b1.Property<Guid>("VendorOnboardingApplicationId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("DecidedByName")
                                .HasColumnType("text");

                            b1.Property<string>("DecidedByUserId")
                                .HasColumnType("text");

                            b1.Property<DateTime?>("DecidedUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)");

                            b1.Property<int>("Order")
                                .HasColumnType("integer");

                            b1.Property<string>("Outcome")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<string>("Reason")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)");

                            b1.Property<bool>("RequiresFinance")
                                .HasColumnType("boolean");

                            b1.HasKey("VendorOnboardingApplicationId", "Id");

                            b1.ToTable("OnboardingReviewSteps", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("VendorOnboardingApplicationId");
                        });

                    b.OwnsMany("eProcure.Domain.Suppliers.VendorAddress", "Addresses", b1 =>
                        {
                            b1.Property<Guid>("VendorOnboardingApplicationId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<bool>("IsPrimary")
                                .HasColumnType("boolean");

                            b1.Property<string>("Line")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Postcode")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("VendorOnboardingApplicationId", "Id");

                            b1.ToTable("OnboardingAddresses", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("VendorOnboardingApplicationId");
                        });

                    b.OwnsMany("eProcure.Domain.Suppliers.VendorBankAccount", "BankAccounts", b1 =>
                        {
                            b1.Property<Guid>("VendorOnboardingApplicationId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("AccountNo")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Bank")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<bool>("IsPrimary")
                                .HasColumnType("boolean");

                            b1.Property<string>("Swift")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("VendorOnboardingApplicationId", "Id");

                            b1.ToTable("OnboardingBankAccounts", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("VendorOnboardingApplicationId");
                        });

                    b.OwnsMany("eProcure.Domain.Suppliers.VendorCertification", "Certifications", b1 =>
                        {
                            b1.Property<Guid>("VendorOnboardingApplicationId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ValidTo")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("VendorOnboardingApplicationId", "Id");

                            b1.ToTable("OnboardingCertifications", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("VendorOnboardingApplicationId");
                        });

                    b.OwnsMany("eProcure.Domain.Suppliers.VendorContact", "Contacts", b1 =>
                        {
                            b1.Property<Guid>("VendorOnboardingApplicationId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<bool>("IsPrimary")
                                .HasColumnType("boolean");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Role")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("VendorOnboardingApplicationId", "Id");

                            b1.ToTable("OnboardingContacts", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("VendorOnboardingApplicationId");
                        });

                    b.Navigation("Addresses");

                    b.Navigation("Answers");

                    b.Navigation("BankAccounts");

                    b.Navigation("Certifications");

                    b.Navigation("Contacts");

                    b.Navigation("Documents");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("eProcure.Domain.Procurement.Asn", b =>
                {
                    b.OwnsMany("eProcure.Domain.Procurement.AsnLine", "Lines", b1 =>
                        {
                            b1.Property<Guid>("AsnId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ItemCode")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("LotNo")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<decimal>("ShippedQty")
                                .HasColumnType("numeric(18,2)");

                            b1.Property<string>("Uom")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("AsnId", "Id");

                            b1.ToTable("AsnLines", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AsnId");
                        });

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("eProcure.Domain.Procurement.Grn", b =>
                {
                    b.OwnsMany("eProcure.Domain.Procurement.GrnLine", "Lines", b1 =>
                        {
                            b1.Property<Guid>("GrnId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Condition")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<decimal>("ExpectedQty")
                                .HasColumnType("numeric(18,2)");

                            b1.Property<string>("ItemCode")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<decimal>("ReceivedQty")
                                .HasColumnType("numeric(18,2)");

                            b1.HasKey("GrnId", "Id");

                            b1.ToTable("GrnLines", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("GrnId");
                        });

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("eProcure.Domain.Procurement.Invoice", b =>
                {
                    b.OwnsMany("eProcure.Domain.Procurement.InvoiceLine", "Lines", b1 =>
                        {
                            b1.Property<Guid>("InvoiceId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ItemCode")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<decimal>("Qty")
                                .HasColumnType("numeric(18,2)");

                            b1.Property<decimal>("UnitPrice")
                                .HasColumnType("numeric(18,2)");

                            b1.Property<string>("Uom")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("InvoiceId", "Id");

                            b1.ToTable("InvoiceLines", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("InvoiceId");
                        });

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("eProcure.Domain.Procurement.PurchaseOrder", b =>
                {
                    b.OwnsMany("eProcure.Domain.Procurement.PoLine", "Lines", b1 =>
                        {
                            b1.Property<Guid>("PurchaseOrderId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<decimal>("InvoicedQty")
                                .HasColumnType("numeric(18,2)");

                            b1.Property<string>("ItemCode")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<decimal>("Qty")
                                .HasColumnType("numeric(18,2)");

                            b1.Property<decimal>("ReceivedQty")
                                .HasColumnType("numeric(18,2)");

                            b1.Property<decimal>("UnitPrice")
                                .HasColumnType("numeric(18,2)");

                            b1.Property<string>("Uom")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("PurchaseOrderId", "Id");

                            b1.ToTable("PoLines", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PurchaseOrderId");
                        });

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("eProcure.Domain.Sourcing.Award", b =>
                {
                    b.OwnsMany("eProcure.Domain.Sourcing.AwardAllocation", "Allocations", b1 =>
                        {
                            b1.Property<Guid>("AwardId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<decimal>("Qty")
                                .HasColumnType("numeric(18,2)");

                            b1.Property<string>("RfqLineCode")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<decimal>("UnitPrice")
                                .HasColumnType("numeric(18,2)");

                            b1.Property<Guid>("VendorId")
                                .HasColumnType("uuid");

                            b1.HasKey("AwardId", "Id");

                            b1.ToTable("AwardAllocations", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AwardId");
                        });

                    b.Navigation("Allocations");
                });

            modelBuilder.Entity("eProcure.Domain.Sourcing.Bid", b =>
                {
                    b.OwnsMany("eProcure.Domain.Sourcing.BidAnswer", "Answers", b1 =>
                        {
                            b1.Property<Guid>("BidId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int>("QuestionOrder")
                                .HasColumnType("integer");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("BidId", "Id");

                            b1.ToTable("BidAnswers", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("BidId");
                        });

                    b.OwnsMany("eProcure.Domain.Sourcing.BidAttachment", "Files", b1 =>
                        {
                            b1.Property<Guid>("BidId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("BidId", "Id");

                            b1.ToTable("BidAttachments", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("BidId");
                        });

                    b.OwnsMany("eProcure.Domain.Sourcing.BidLine", "Lines", b1 =>
                        {
                            b1.Property<Guid>("BidId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("AltItem")
                                .HasColumnType("text");

                            b1.Property<bool>("Bidding")
                                .HasColumnType("boolean");

                            b1.Property<string>("ItemCode")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<bool>("Partial")
                                .HasColumnType("boolean");

                            b1.Property<decimal>("Price")
                                .HasColumnType("numeric(18,2)");

                            b1.Property<decimal>("Qty")
                                .HasColumnType("numeric(18,2)");

                            b1.HasKey("BidId", "Id");

                            b1.ToTable("BidLines", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("BidId");
                        });

                    b.Navigation("Answers");

                    b.Navigation("Files");

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("eProcure.Domain.Sourcing.FormTemplate", b =>
                {
                    b.OwnsMany("eProcure.Domain.Sourcing.FormItem", "Items", b1 =>
                        {
                            b1.Property<Guid>("FormTemplateId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("ConfigJson")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Group")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Help")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Label")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("Order")
                                .HasColumnType("integer");

                            b1.Property<bool>("Required")
                                .HasColumnType("boolean");

                            b1.Property<string>("Section")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("FormTemplateId", "Id");

                            b1.ToTable("FormTemplateItems", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("FormTemplateId");
                        });

                    b.Navigation("Items");
                });

            modelBuilder.Entity("eProcure.Domain.Sourcing.PurchaseRequisition", b =>
                {
                    b.OwnsMany("eProcure.Domain.Sourcing.PrLine", "Lines", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<decimal>("EstUnitPrice")
                                .HasColumnType("numeric(18,2)");

                            b1.Property<string>("ItemCode")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("LifecycleStatus")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<Guid>("PurchaseRequisitionId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Qty")
                                .HasColumnType("numeric(18,2)");

                            b1.Property<string>("Ref")
                                .HasColumnType("text");

                            b1.Property<string>("Uom")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)");

                            b1.Property<DateTime?>("UpdatedUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("Id");

                            b1.HasIndex("ItemCode");

                            b1.HasIndex("LifecycleStatus");

                            b1.HasIndex("PurchaseRequisitionId");

                            b1.ToTable("PrLines", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PurchaseRequisitionId");
                        });

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("eProcure.Domain.Sourcing.Rfq", b =>
                {
                    b.OwnsMany("eProcure.Domain.Sourcing.FormItem", "FormItems", b1 =>
                        {
                            b1.Property<Guid>("RfqId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("ConfigJson")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Group")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Help")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Label")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("Order")
                                .HasColumnType("integer");

                            b1.Property<bool>("Required")
                                .HasColumnType("boolean");

                            b1.Property<string>("Section")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("RfqId", "Id");

                            b1.ToTable("RfqFormItems", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RfqId");
                        });

                    b.OwnsMany("eProcure.Domain.Sourcing.RfqLine", "Lines", b1 =>
                        {
                            b1.Property<Guid>("RfqId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ItemCode")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("LineCode")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)");

                            b1.Property<string>("PrRef")
                                .HasColumnType("text");

                            b1.Property<decimal>("Qty")
                                .HasColumnType("numeric(18,2)");

                            b1.Property<string>("SourcePrLineIds")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Uom")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("RfqId", "Id");

                            b1.ToTable("RfqLines", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RfqId");
                        });

                    b.Navigation("FormItems");

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("eProcure.Domain.Suppliers.Vendor", b =>
                {
                    b.OwnsMany("eProcure.Domain.Suppliers.VendorAddress", "Addresses", b1 =>
                        {
                            b1.Property<Guid>("VendorId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<bool>("IsPrimary")
                                .HasColumnType("boolean");

                            b1.Property<string>("Line")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Postcode")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("VendorId", "Id");

                            b1.ToTable("VendorAddresses", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("VendorId");
                        });

                    b.OwnsMany("eProcure.Domain.Suppliers.VendorBankAccount", "BankAccounts", b1 =>
                        {
                            b1.Property<Guid>("VendorId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("AccountNo")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Bank")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<bool>("IsPrimary")
                                .HasColumnType("boolean");

                            b1.Property<string>("Swift")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("VendorId", "Id");

                            b1.ToTable("VendorBankAccounts", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("VendorId");
                        });

                    b.OwnsMany("eProcure.Domain.Suppliers.VendorCertification", "Certifications", b1 =>
                        {
                            b1.Property<Guid>("VendorId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ValidTo")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("VendorId", "Id");

                            b1.ToTable("VendorCertifications", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("VendorId");
                        });

                    b.OwnsMany("eProcure.Domain.Suppliers.VendorContact", "Contacts", b1 =>
                        {
                            b1.Property<Guid>("VendorId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<bool>("IsPrimary")
                                .HasColumnType("boolean");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Role")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("VendorId", "Id");

                            b1.ToTable("VendorContacts", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("VendorId");
                        });

                    b.OwnsMany("eProcure.Domain.Suppliers.VendorCurrency", "Currencies", b1 =>
                        {
                            b1.Property<Guid>("VendorId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<bool>("IsPrimary")
                                .HasColumnType("boolean");

                            b1.HasKey("VendorId", "Id");

                            b1.ToTable("VendorCurrencies", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("VendorId");
                        });

                    b.OwnsOne("eProcure.Domain.Suppliers.VendorPerformance", "Performance", b1 =>
                        {
                            b1.Property<Guid>("VendorId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Breaches")
                                .HasColumnType("integer");

                            b1.Property<int>("Lead")
                                .HasColumnType("integer");

                            b1.Property<int>("Otd")
                                .HasColumnType("integer");

                            b1.Property<int>("Pos")
                                .HasColumnType("integer");

                            b1.Property<int>("Quality")
                                .HasColumnType("integer");

                            b1.Property<int>("Response")
                                .HasColumnType("integer");

                            b1.Property<decimal>("SpendYtd")
                                .HasColumnType("numeric(18,2)");

                            b1.Property<int>("WinRate")
                                .HasColumnType("integer");

                            b1.HasKey("VendorId");

                            b1.ToTable("Vendors");

                            b1.WithOwner()
                                .HasForeignKey("VendorId");
                        });

                    b.Navigation("Addresses");

                    b.Navigation("BankAccounts");

                    b.Navigation("Certifications");

                    b.Navigation("Contacts");

                    b.Navigation("Currencies");

                    b.Navigation("Performance")
                        .IsRequired();
                });

            modelBuilder.Entity("eProcure.Domain.Suppliers.VendorUser", b =>
                {
                    b.HasOne("eProcure.Domain.Suppliers.Vendor", null)
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("eProcure.Domain.Onboarding.VendorOnboardingApplication", b =>
                {
                    b.Navigation("Financial");

                    b.Navigation("Rounds");
                });
#pragma warning restore 612, 618
        }
    }
}
