// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using eProcure.Infrastructure.Persistence;

#nullable disable

namespace eProcure.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260628124106_Slice03_Bids")]
    partial class Slice03_Bids
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("eProcure.Domain.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ActorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("After")
                        .HasColumnType("text");

                    b.Property<string>("Before")
                        .HasColumnType("text");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UtcTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("UtcTimestamp");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("AuditEntries", (string)null);
                });

            modelBuilder.Entity("eProcure.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("eProcure.Domain.NumberSequence", b =>
                {
                    b.Property<string>("Prefix")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.Property<int>("LastValue")
                        .HasColumnType("integer");

                    b.HasKey("Prefix", "Year");

                    b.ToTable("NumberSequences", (string)null);
                });

            modelBuilder.Entity("eProcure.Domain.Sourcing.Bid", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Lead")
                        .HasColumnType("integer");

                    b.Property<Guid>("RfqId")
                        .HasColumnType("uuid");

                    b.Property<bool>("SavedDraft")
                        .HasColumnType("boolean");

                    b.Property<bool>("Submitted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("SubmittedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid");

                    b.Property<int>("Warranty")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("RfqId", "VendorId")
                        .IsUnique();

                    b.ToTable("Bids", (string)null);
                });

            modelBuilder.Entity("eProcure.Domain.Sourcing.FormTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CommercialSections")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TechnicalSections")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("FormTemplates", (string)null);
                });

            modelBuilder.Entity("eProcure.Domain.Sourcing.PurchaseRequisition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CostCentre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Job")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Memo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Project")
                        .HasColumnType("text");

                    b.Property<string>("RaisedDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Requestor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequiredDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("PurchaseRequisitions", (string)null);
                });

            modelBuilder.Entity("eProcure.Domain.Sourcing.Rfq", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ClosesUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CommercialEvaluatorIds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("CommercialOpened")
                        .HasColumnType("boolean");

                    b.Property<string>("CommercialSections")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Envelope")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("InvitedVendorIds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("OpensUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PrRefs")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("TechFinalized")
                        .HasColumnType("boolean");

                    b.Property<string>("TechnicalEvaluatorIds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TechnicalSections")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Rfqs", (string)null);
                });

            modelBuilder.Entity("eProcure.Domain.Suppliers.SwecCategory", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsLeaf")
                        .HasColumnType("boolean");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ParentCode")
                        .HasColumnType("text");

                    b.Property<string>("PathText")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.HasKey("Code");

                    b.ToTable("SwecCategories", (string)null);
                });

            modelBuilder.Entity("eProcure.Domain.Suppliers.Vendor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Categories")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CreditLimit")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("LlrcTier")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PaymentTerms")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Rating")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RegisteredName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RegistrationNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TaxId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Vendors", (string)null);
                });

            modelBuilder.Entity("eProcure.Domain.Suppliers.VendorUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("VendorId");

                    b.ToTable("VendorUsers", (string)null);
                });

            modelBuilder.Entity("eProcure.Domain.Sourcing.Bid", b =>
                {
                    b.OwnsMany("eProcure.Domain.Sourcing.BidAnswer", "Answers", b1 =>
                        {
                            b1.Property<Guid>("BidId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int>("QuestionOrder")
                                .HasColumnType("integer");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("BidId", "Id");

                            b1.ToTable("BidAnswers", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("BidId");
                        });

                    b.OwnsMany("eProcure.Domain.Sourcing.BidAttachment", "Files", b1 =>
                        {
                            b1.Property<Guid>("BidId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("BidId", "Id");

                            b1.ToTable("BidAttachments", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("BidId");
                        });

                    b.OwnsMany("eProcure.Domain.Sourcing.BidLine", "Lines", b1 =>
                        {
                            b1.Property<Guid>("BidId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("AltItem")
                                .HasColumnType("text");

                            b1.Property<bool>("Bidding")
                                .HasColumnType("boolean");

                            b1.Property<string>("ItemCode")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<bool>("Partial")
                                .HasColumnType("boolean");

                            b1.Property<decimal>("Price")
                                .HasColumnType("numeric(18,2)");

                            b1.Property<decimal>("Qty")
                                .HasColumnType("numeric(18,2)");

                            b1.HasKey("BidId", "Id");

                            b1.ToTable("BidLines", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("BidId");
                        });

                    b.Navigation("Answers");

                    b.Navigation("Files");

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("eProcure.Domain.Sourcing.FormTemplate", b =>
                {
                    b.OwnsMany("eProcure.Domain.Sourcing.FormItem", "Items", b1 =>
                        {
                            b1.Property<Guid>("FormTemplateId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("ConfigJson")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Group")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Help")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Label")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("Order")
                                .HasColumnType("integer");

                            b1.Property<bool>("Required")
                                .HasColumnType("boolean");

                            b1.Property<string>("Section")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("FormTemplateId", "Id");

                            b1.ToTable("FormTemplateItems", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("FormTemplateId");
                        });

                    b.Navigation("Items");
                });

            modelBuilder.Entity("eProcure.Domain.Sourcing.PurchaseRequisition", b =>
                {
                    b.OwnsMany("eProcure.Domain.Sourcing.PrLine", "Lines", b1 =>
                        {
                            b1.Property<Guid>("PurchaseRequisitionId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<decimal>("EstUnitPrice")
                                .HasColumnType("numeric(18,2)");

                            b1.Property<string>("ItemCode")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<decimal>("Qty")
                                .HasColumnType("numeric(18,2)");

                            b1.Property<string>("Ref")
                                .HasColumnType("text");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Uom")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("PurchaseRequisitionId", "Id");

                            b1.ToTable("PrLines", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PurchaseRequisitionId");
                        });

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("eProcure.Domain.Sourcing.Rfq", b =>
                {
                    b.OwnsMany("eProcure.Domain.Sourcing.FormItem", "FormItems", b1 =>
                        {
                            b1.Property<Guid>("RfqId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("ConfigJson")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Group")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Help")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Label")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("Order")
                                .HasColumnType("integer");

                            b1.Property<bool>("Required")
                                .HasColumnType("boolean");

                            b1.Property<string>("Section")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("RfqId", "Id");

                            b1.ToTable("RfqFormItems", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RfqId");
                        });

                    b.OwnsMany("eProcure.Domain.Sourcing.RfqLine", "Lines", b1 =>
                        {
                            b1.Property<Guid>("RfqId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ItemCode")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("PrRef")
                                .HasColumnType("text");

                            b1.Property<decimal>("Qty")
                                .HasColumnType("numeric(18,2)");

                            b1.Property<string>("Uom")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("RfqId", "Id");

                            b1.ToTable("RfqLines", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RfqId");
                        });

                    b.Navigation("FormItems");

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("eProcure.Domain.Suppliers.Vendor", b =>
                {
                    b.OwnsMany("eProcure.Domain.Suppliers.VendorAddress", "Addresses", b1 =>
                        {
                            b1.Property<Guid>("VendorId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<bool>("IsPrimary")
                                .HasColumnType("boolean");

                            b1.Property<string>("Line")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Postcode")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("VendorId", "Id");

                            b1.ToTable("VendorAddresses", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("VendorId");
                        });

                    b.OwnsMany("eProcure.Domain.Suppliers.VendorBankAccount", "BankAccounts", b1 =>
                        {
                            b1.Property<Guid>("VendorId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("AccountNo")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Bank")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<bool>("IsPrimary")
                                .HasColumnType("boolean");

                            b1.Property<string>("Swift")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("VendorId", "Id");

                            b1.ToTable("VendorBankAccounts", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("VendorId");
                        });

                    b.OwnsMany("eProcure.Domain.Suppliers.VendorCertification", "Certifications", b1 =>
                        {
                            b1.Property<Guid>("VendorId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ValidTo")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("VendorId", "Id");

                            b1.ToTable("VendorCertifications", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("VendorId");
                        });

                    b.OwnsMany("eProcure.Domain.Suppliers.VendorContact", "Contacts", b1 =>
                        {
                            b1.Property<Guid>("VendorId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<bool>("IsPrimary")
                                .HasColumnType("boolean");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Role")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("VendorId", "Id");

                            b1.ToTable("VendorContacts", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("VendorId");
                        });

                    b.OwnsMany("eProcure.Domain.Suppliers.VendorCurrency", "Currencies", b1 =>
                        {
                            b1.Property<Guid>("VendorId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<bool>("IsPrimary")
                                .HasColumnType("boolean");

                            b1.HasKey("VendorId", "Id");

                            b1.ToTable("VendorCurrencies", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("VendorId");
                        });

                    b.OwnsOne("eProcure.Domain.Suppliers.VendorPerformance", "Performance", b1 =>
                        {
                            b1.Property<Guid>("VendorId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Breaches")
                                .HasColumnType("integer");

                            b1.Property<int>("Lead")
                                .HasColumnType("integer");

                            b1.Property<int>("Otd")
                                .HasColumnType("integer");

                            b1.Property<int>("Pos")
                                .HasColumnType("integer");

                            b1.Property<int>("Quality")
                                .HasColumnType("integer");

                            b1.Property<int>("Response")
                                .HasColumnType("integer");

                            b1.Property<decimal>("SpendYtd")
                                .HasColumnType("numeric(18,2)");

                            b1.Property<int>("WinRate")
                                .HasColumnType("integer");

                            b1.HasKey("VendorId");

                            b1.ToTable("Vendors");

                            b1.WithOwner()
                                .HasForeignKey("VendorId");
                        });

                    b.Navigation("Addresses");

                    b.Navigation("BankAccounts");

                    b.Navigation("Certifications");

                    b.Navigation("Contacts");

                    b.Navigation("Currencies");

                    b.Navigation("Performance")
                        .IsRequired();
                });

            modelBuilder.Entity("eProcure.Domain.Suppliers.VendorUser", b =>
                {
                    b.HasOne("eProcure.Domain.Suppliers.Vendor", null)
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
