using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace eProcure.Infrastructure.Persistence.Migrations
{
    /// <summary>
    /// Slice H T1 (DBA-5): give the nine owned line collections a stable <c>Guid Id</c> grain key,
    /// following the <c>PrLine</c> precedent, so they can serve as fact-table grain instead of being
    /// addressed by ordinal position.
    ///
    /// Each table currently has a composite PK <c>(OwnerId, Id int)</c> where <c>Id</c> is an EF shadow
    /// identity ordinal. The scaffolder emitted <c>AlterColumn&lt;Guid&gt;("Id", oldType: int)</c>, which
    /// Postgres cannot execute (no int→uuid cast). This hand-authored version does the swap
    /// NON-DESTRUCTIVELY and in place — rows and their parent (owner FK) associations are preserved;
    /// only the meaningless surrogate ordinal is replaced with a fresh uuid:
    ///   drop the composite PK → drop identity on "Id" → retype int→uuid assigning gen_random_uuid()
    ///   per existing row → add the single-column PK → index the owner FK.
    /// There is NO DropTable/CreateTable, so no line data is dropped and recreated (proven with a
    /// before/after row-count + content-fingerprint over Up→Down→Up on a seeded DB).
    ///
    /// The key is client-assigned (<c>= Guid.NewGuid()</c>, mapped ValueGeneratedNever) because the
    /// line services REPLACE the owned collection on edit; a store-generated key would make EF treat
    /// the fresh client Guids as existing rows and UPDATE (0 rows) instead of INSERT. So there is no
    /// column DEFAULT — new rows always arrive with their key set.
    ///
    /// Down() restores the prior key configuration: it drops the uuid "Id" and re-adds an int identity
    /// ordinal + the composite PK. Line CONTENTS and owner associations survive the round-trip; only the
    /// surrogate ordinal values are regenerated (they carry no business meaning).
    /// </summary>
    public partial class StableLineKeys : Migration
    {
        // (owned table, owner FK column) — the nine collections gaining a stable Guid grain key.
        private static readonly (string Table, string OwnerFk)[] Owned =
        [
            ("RfqLines", "RfqId"),
            ("BidLines", "BidId"),
            ("BidAnswers", "BidId"),
            ("BidAttachments", "BidId"),
            ("PoLines", "PurchaseOrderId"),
            ("AsnLines", "AsnId"),
            ("GrnLines", "GrnId"),
            ("InvoiceLines", "InvoiceId"),
            ("AwardAllocations", "AwardId"),
        ];

        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            foreach (var (table, fk) in Owned)
            {
                migrationBuilder.Sql($@"
                    ALTER TABLE ""{table}"" DROP CONSTRAINT ""PK_{table}"";
                    ALTER TABLE ""{table}"" ALTER COLUMN ""Id"" DROP IDENTITY IF EXISTS;
                    ALTER TABLE ""{table}"" ALTER COLUMN ""Id"" TYPE uuid USING gen_random_uuid();
                    ALTER TABLE ""{table}"" ADD CONSTRAINT ""PK_{table}"" PRIMARY KEY (""Id"");
                    CREATE INDEX ""IX_{table}_{fk}"" ON ""{table}"" (""{fk}"");");
            }
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            foreach (var (table, fk) in Owned)
            {
                migrationBuilder.Sql($@"
                    DROP INDEX ""IX_{table}_{fk}"";
                    ALTER TABLE ""{table}"" DROP CONSTRAINT ""PK_{table}"";
                    ALTER TABLE ""{table}"" DROP COLUMN ""Id"";
                    ALTER TABLE ""{table}"" ADD COLUMN ""Id"" integer GENERATED BY DEFAULT AS IDENTITY;
                    ALTER TABLE ""{table}"" ADD CONSTRAINT ""PK_{table}"" PRIMARY KEY (""{fk}"", ""Id"");");
            }
        }
    }
}
