namespace FSH.Modules.Sourcing.Contracts.Dtos;

public sealed record RequisitionDto(
    Guid Id,
    string Code,
    string Requestor,
    string Department,
    string? DepartmentCode,
    string Location,
    string? LocationCode,
    string Category,
    string? CategoryCode,
    string Job,
    string? JobCode,
    string Memo,
    string CostCentre,
    string? Project,
    Guid? EntryFormId,
    DateOnly? RaisedOn,
    DateOnly? RequiredOn,
    bool Submitted,
    DateTime? SubmittedUtc,
    string HeaderStatus,
    string Currency,
    IReadOnlyList<PrLineDto> Lines,
    DateTime CreatedUtc,
    DateTime UpdatedUtc,
    Guid? ShipToLocationId = null,
    Guid? ShipToAddressId = null,
    string? ShipToAdhoc = null,
    string? ShipTo = null);

public sealed record RequisitionListItemDto(
    Guid Id,
    string Code,
    string Requestor,
    string Department,
    string Location,
    string Category,
    string Job,
    DateOnly? RequiredOn,
    string HeaderStatus,
    bool Submitted,
    int LineCount,
    int OpenLineCount,
    DateTime CreatedUtc);
