namespace FSH.Modules.Sourcing.Contracts.Dtos;

public sealed record RfqDetailDto(
    Guid Id,
    string Code,
    string Title,
    string Envelope,
    string Status,
    string Currency,
    decimal? ExchangeRateToBase,
    string BaseCurrency,
    string? OwnerUserId,
    DateTime? OpensUtc,
    DateTime? ClosesUtc,
    DateTime? OriginalClosesUtc,
    int ExtensionCount,
    DateTime? ReleasedUtc,
    DateTime? ClosedUtc,
    IReadOnlyList<string> PrRefs,
    IReadOnlyList<RfqLineDto> Lines,
    IReadOnlyList<FormItemDto> FormItems,
    IReadOnlyList<string> TechnicalSections,
    IReadOnlyList<string> CommercialSections,
    IReadOnlyList<string> TechnicalEvaluatorIds,
    IReadOnlyList<string> CommercialEvaluatorIds,
    bool TechnicalOpened,
    bool TechFinalized,
    bool CommercialOpened,
    IReadOnlyList<RfqInvitationDto> Invitations,
    IReadOnlyList<RfqEventDto> Events,
    DateTime CreatedUtc,
    DateTime UpdatedUtc,
    DateTime? ClarificationDeadlineUtc = null,
    int? BidValidityDays = null,
    bool PartialBidsAllowed = true,
    Guid? IncotermId = null,
    string? IncotermCode = null,
    string? IncotermSuffix = null,
    string? Incoterm = null);
