// <auto-generated />
using System;
using FSH.Modules.Suppliers.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FSH.Starter.Migrations.PostgreSQL.Suppliers
{
    [DbContext(typeof(SuppliersDbContext))]
    [Migration("20260805030722_SuppliersFshAudit")]
    partial class SuppliersFshAudit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("suppliers")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("OnboardingApplicationCodeSeq", "suppliers");

            modelBuilder.HasSequence("VendorCodeSeq", "suppliers")
                .StartsAt(10001L);

            modelBuilder.HasSequence("VendorUserCodeSeq", "suppliers");

            modelBuilder.Entity("FSH.Modules.Suppliers.Domain.Onboarding.OnboardingClarificationRound", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("LastModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("RaisedByName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RaisedByUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("RaisedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RespondedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RoundNo")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("ApplicationId", "RoundNo");

                    b.ToTable("OnboardingClarificationRounds", "suppliers");

                    b.HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("FSH.Modules.Suppliers.Domain.Onboarding.VendorFinancialAssessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("LastModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("VendorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId")
                        .IsUnique()
                        .HasDatabaseName("IX_VendorFinancialAssessments_ApplicationId1");

                    b.HasIndex("ApplicationId", "TenantId")
                        .IsUnique()
                        .HasDatabaseName("IX_VendorFinancialAssessments_ApplicationId");

                    b.ToTable("VendorFinancialAssessments", "suppliers");

                    b.HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("FSH.Modules.Suppliers.Domain.Onboarding.VendorOnboardingApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Categories")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("CityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DecisionUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("InvitationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("PromotedVendorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RegisteredName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RegistrationNo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("RejectReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("SelectedTemplateIds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("StateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("SubmittedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TaxId")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("LastModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CountryCode");

                    b.HasIndex("CreatedOnUtc");

                    b.HasIndex("DecisionUtc");

                    b.HasIndex("InvitationId");

                    b.HasIndex("Source");

                    b.HasIndex("Status");

                    b.HasIndex("SubmittedUtc");

                    b.HasIndex("Type");

                    b.HasIndex("Code", "TenantId")
                        .IsUnique()
                        .HasDatabaseName("IX_VendorOnboardingApplications_Code");

                    b.ToTable("VendorOnboardingApplications", "suppliers");

                    b.HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("FSH.Modules.Suppliers.Domain.Onboarding.VendorOnboardingInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("ExpiresUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InvitedByName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("InvitedByUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("LastModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("OpenedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SelectedTemplateIds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("CreatedOnUtc");

                    b.HasIndex("InvitedByUserId");

                    b.HasIndex("Status");

                    b.HasIndex("TokenHash", "TenantId")
                        .IsUnique()
                        .HasDatabaseName("IX_VendorOnboardingInvitations_TokenHash");

                    b.ToTable("VendorOnboardingInvitations", "suppliers");

                    b.HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("FSH.Modules.Suppliers.Domain.SwecCategory", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsLeaf")
                        .HasColumnType("boolean");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("LastModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ParentCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PathText")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Code");

                    b.HasIndex("ParentCode");

                    b.ToTable("SwecCategories", "suppliers");

                    b.HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("FSH.Modules.Suppliers.Domain.Vendor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Categories")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("CityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CreditLimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("EntryFormId")
                        .HasColumnType("uuid");

                    b.Property<string>("LlrcTier")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PaymentTerms")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Rating")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RegisteredName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RegistrationNo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("StateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TaxId")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("LastModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CountryCode");

                    b.HasIndex("Code", "TenantId")
                        .IsUnique()
                        .HasDatabaseName("IX_Vendors_Code");

                    b.ToTable("Vendors", "suppliers");

                    b.HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("FSH.Modules.Suppliers.Domain.VendorUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("IdentityUserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("LastModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VendorId");

                    b.HasIndex("Code", "TenantId")
                        .IsUnique()
                        .HasDatabaseName("IX_VendorUsers_Code");

                    b.HasIndex("Email", "TenantId")
                        .IsUnique()
                        .HasDatabaseName("IX_VendorUsers_Email");

                    b.ToTable("VendorUsers", "suppliers");

                    b.HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("FSH.Modules.Suppliers.Domain.Onboarding.OnboardingClarificationRound", b =>
                {
                    b.HasOne("FSH.Modules.Suppliers.Domain.Onboarding.VendorOnboardingApplication", null)
                        .WithMany("Rounds")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("FSH.Modules.Suppliers.Domain.Onboarding.OnboardingClarificationItem", "Items", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("Request")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)");

                            b1.Property<string>("Response")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)");

                            b1.Property<Guid>("RoundId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Topic")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)");

                            b1.HasKey("Id");

                            b1.HasIndex("RoundId");

                            b1.ToTable("OnboardingClarificationItems", "suppliers");

                            b1.WithOwner()
                                .HasForeignKey("RoundId");
                        });

                    b.Navigation("Items");
                });

            modelBuilder.Entity("FSH.Modules.Suppliers.Domain.Onboarding.VendorFinancialAssessment", b =>
                {
                    b.HasOne("FSH.Modules.Suppliers.Domain.Onboarding.VendorOnboardingApplication", null)
                        .WithOne("Financial")
                        .HasForeignKey("FSH.Modules.Suppliers.Domain.Onboarding.VendorFinancialAssessment", "ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("FSH.Modules.Suppliers.Domain.Onboarding.FinancialSnapshot", "Snapshots", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("AsOfUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("AssessmentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Band")
                                .IsRequired()
                                .HasMaxLength(5)
                                .HasColumnType("character varying(5)");

                            b1.Property<string>("Risk")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<int>("Score")
                                .HasColumnType("integer");

                            b1.Property<string>("Stage")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<string>("Statement")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)");

                            b1.Property<double>("WeightedZ")
                                .HasColumnType("double precision");

                            b1.HasKey("Id");

                            b1.HasIndex("AssessmentId");

                            b1.ToTable("OnboardingFinancialSnapshots", "suppliers");

                            b1.WithOwner()
                                .HasForeignKey("AssessmentId");
                        });

                    b.OwnsMany("FSH.Modules.Suppliers.Domain.Onboarding.FinancialYearFigures", "Years", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<Guid>("AssessmentId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("CurrentAssets")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("CurrentLiabilities")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("Ebit")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("Equity")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("FixedAssets")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("Inventory")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("NetProfit")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("RetainedEarnings")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("Revenue")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("TotalAssets")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("TotalLiabilities")
                                .HasColumnType("numeric");

                            b1.Property<int>("YearIndex")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("AssessmentId");

                            b1.HasIndex("YearIndex");

                            b1.ToTable("OnboardingFinancialYears", "suppliers");

                            b1.WithOwner()
                                .HasForeignKey("AssessmentId");
                        });

                    b.Navigation("Snapshots");

                    b.Navigation("Years");
                });

            modelBuilder.Entity("FSH.Modules.Suppliers.Domain.Onboarding.VendorOnboardingApplication", b =>
                {
                    b.OwnsMany("FSH.Modules.Suppliers.Domain.Onboarding.OnboardingAnswer", "Answers", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<Guid>("ApplicationId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("FormTemplateId")
                                .HasColumnType("uuid");

                            b1.Property<int>("QuestionOrder")
                                .HasColumnType("integer");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("character varying(4000)");

                            b1.HasKey("Id");

                            b1.HasIndex("ApplicationId");

                            b1.HasIndex("FormTemplateId");

                            b1.ToTable("OnboardingAnswers", "suppliers");

                            b1.WithOwner()
                                .HasForeignKey("ApplicationId");
                        });

                    b.OwnsMany("FSH.Modules.Suppliers.Domain.Onboarding.OnboardingDocument", "Documents", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<Guid>("ApplicationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasMaxLength(260)
                                .HasColumnType("character varying(260)");

                            b1.Property<string>("Key")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)");

                            b1.Property<string>("StorageKey")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<DateTime>("UploadedUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("Id");

                            b1.HasIndex("ApplicationId");

                            b1.ToTable("OnboardingDocuments", "suppliers");

                            b1.WithOwner()
                                .HasForeignKey("ApplicationId");
                        });

                    b.OwnsMany("FSH.Modules.Suppliers.Domain.Onboarding.OnboardingReviewStep", "Steps", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<Guid>("ApplicationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("DecidedByName")
                                .HasColumnType("text");

                            b1.Property<string>("DecidedByUserId")
                                .HasColumnType("text");

                            b1.Property<DateTime?>("DecidedUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)");

                            b1.Property<int>("Order")
                                .HasColumnType("integer");

                            b1.Property<string>("Outcome")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<string>("Reason")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)");

                            b1.Property<bool>("RequiresFinance")
                                .HasColumnType("boolean");

                            b1.HasKey("Id");

                            b1.HasIndex("ApplicationId");

                            b1.HasIndex("DecidedByUserId");

                            b1.ToTable("OnboardingReviewSteps", "suppliers");

                            b1.WithOwner()
                                .HasForeignKey("ApplicationId");
                        });

                    b.OwnsMany("FSH.Modules.Suppliers.Domain.VendorAddress", "Addresses", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<Guid>("ApplicationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<Guid?>("CityId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)");

                            b1.Property<bool>("IsPrimary")
                                .HasColumnType("boolean");

                            b1.Property<string>("Line")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)");

                            b1.Property<string>("Postcode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<Guid?>("StateId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.HasKey("Id");

                            b1.HasIndex("ApplicationId");

                            b1.ToTable("OnboardingAddresses", "suppliers");

                            b1.WithOwner()
                                .HasForeignKey("ApplicationId");
                        });

                    b.OwnsMany("FSH.Modules.Suppliers.Domain.VendorBankAccount", "BankAccounts", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("AccountNo")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<Guid>("ApplicationId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("BankId")
                                .HasColumnType("uuid");

                            b1.Property<string>("BankName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)");

                            b1.Property<bool>("IsPrimary")
                                .HasColumnType("boolean");

                            b1.Property<string>("Swift")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.HasKey("Id");

                            b1.HasIndex("ApplicationId");

                            b1.ToTable("OnboardingBankAccounts", "suppliers");

                            b1.WithOwner()
                                .HasForeignKey("ApplicationId");
                        });

                    b.OwnsMany("FSH.Modules.Suppliers.Domain.VendorCertification", "Certifications", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<Guid>("ApplicationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<string>("ValidTo")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.HasKey("Id");

                            b1.HasIndex("ApplicationId");

                            b1.ToTable("OnboardingCertifications", "suppliers");

                            b1.WithOwner()
                                .HasForeignKey("ApplicationId");
                        });

                    b.OwnsMany("FSH.Modules.Suppliers.Domain.VendorContact", "Contacts", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<Guid>("ApplicationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<bool>("IsPrimary")
                                .HasColumnType("boolean");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Role")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("Id");

                            b1.HasIndex("ApplicationId");

                            b1.ToTable("OnboardingContacts", "suppliers");

                            b1.WithOwner()
                                .HasForeignKey("ApplicationId");
                        });

                    b.Navigation("Addresses");

                    b.Navigation("Answers");

                    b.Navigation("BankAccounts");

                    b.Navigation("Certifications");

                    b.Navigation("Contacts");

                    b.Navigation("Documents");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("FSH.Modules.Suppliers.Domain.Vendor", b =>
                {
                    b.OwnsMany("FSH.Modules.Suppliers.Domain.VendorAddress", "Addresses", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<Guid?>("CityId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)");

                            b1.Property<bool>("IsPrimary")
                                .HasColumnType("boolean");

                            b1.Property<string>("Line")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)");

                            b1.Property<string>("Postcode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<Guid?>("StateId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<Guid>("VendorId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("CityId");

                            b1.HasIndex("VendorId");

                            b1.ToTable("VendorAddresses", "suppliers");

                            b1.WithOwner()
                                .HasForeignKey("VendorId");
                        });

                    b.OwnsMany("FSH.Modules.Suppliers.Domain.VendorBankAccount", "BankAccounts", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("AccountNo")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<Guid>("BankId")
                                .HasColumnType("uuid");

                            b1.Property<string>("BankName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)");

                            b1.Property<bool>("IsPrimary")
                                .HasColumnType("boolean");

                            b1.Property<string>("Swift")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<Guid>("VendorId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("BankId");

                            b1.HasIndex("VendorId");

                            b1.ToTable("VendorBankAccounts", "suppliers");

                            b1.WithOwner()
                                .HasForeignKey("VendorId");
                        });

                    b.OwnsMany("FSH.Modules.Suppliers.Domain.VendorCertification", "Certifications", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<string>("ValidTo")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<Guid>("VendorId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("VendorId");

                            b1.ToTable("VendorCertifications", "suppliers");

                            b1.WithOwner()
                                .HasForeignKey("VendorId");
                        });

                    b.OwnsMany("FSH.Modules.Suppliers.Domain.VendorContact", "Contacts", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<bool>("IsPrimary")
                                .HasColumnType("boolean");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Role")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<Guid>("VendorId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("VendorId");

                            b1.ToTable("VendorContacts", "suppliers");

                            b1.WithOwner()
                                .HasForeignKey("VendorId");
                        });

                    b.OwnsMany("FSH.Modules.Suppliers.Domain.VendorCurrency", "Currencies", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)");

                            b1.Property<bool>("IsPrimary")
                                .HasColumnType("boolean");

                            b1.Property<Guid>("VendorId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("VendorId");

                            b1.ToTable("VendorCurrencies", "suppliers");

                            b1.WithOwner()
                                .HasForeignKey("VendorId");
                        });

                    b.Navigation("Addresses");

                    b.Navigation("BankAccounts");

                    b.Navigation("Certifications");

                    b.Navigation("Contacts");

                    b.Navigation("Currencies");
                });

            modelBuilder.Entity("FSH.Modules.Suppliers.Domain.VendorUser", b =>
                {
                    b.HasOne("FSH.Modules.Suppliers.Domain.Vendor", null)
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FSH.Modules.Suppliers.Domain.Onboarding.VendorOnboardingApplication", b =>
                {
                    b.Navigation("Financial");

                    b.Navigation("Rounds");
                });
#pragma warning restore 612, 618
        }
    }
}
